import { CandidateDetail } from '../components';
import {
  AppliedJob,
  CandidatePage,
  CompanyPage,
  JobSearchPage,
  CompanyDetailJob,
  CompanyProfilePage,
  CandidateProfilePage,
  PendingJob,
  CompanyHome,
  CandidateHome,
  PendingCandidate,
  OfferingJobPage,
  ManageAccount,
  ManageJob,
} from '../pages';
const companies = [
  {
    idCompany: 1,
    username: 'tungba2',
    name: 'VNG',
    email: 'vinagame@gmail.com',
    image: 'https://www.logodesign.net/logo/line-art-house-roof-and-buildings-4485ld.png',
    location: 'Ha Noi',
    jobsMain: 'Java,Javascript,Python',
    contactInfo: '0965656565',
    intro: 'IT Company about Game product top 1 Viet Nam',
    offeringJob: '',
    pendingCandidate: '',
    appliedCandidate: null,
  },
  {
    idCompany: 7,
    username: 'fptsoftware',
    name: 'FPT Software',
    email: 'fptshopware@gmail.com',
    image: 'https://cdn.topcv.vn/140/company_logos/fpt-software-6073b38a10cb4.jpg',
    location: 'Ha Noi',
    jobsMain: 'C,Java,NodeJS,ReactJS',
    contactInfo: '0965656565',
    intro:
      'FPT Software là công ty thành viên thuộc Tập đoàn FPT. Được thành lập từ năm 1999, FPT Software hiện là công ty chuyên cung cấp các dịch vụ và giải pháp phần mềm cho các khách hàng quốc tế, với hơn 25.500 nhân viên, hiện diện tại 27 quốc gia trên toàn cầu',
    offeringJob: null,
    pendingCandidate: null,
    appliedCandidate: null,
  },
  {
    idCompany: 8,
    username: 'vietteltelecom',
    name: 'Viettel Telecom',
    email: 'vietteltelecom@gmail.com',
    image: 'https://cdn.topcv.vn/140/company_logos/khoi-cong-nghe-thong-tin-viettel-telecom-618b4ba16e8b4.jpg',
    location: 'Ha Noi',
    jobsMain: 'C,Java,Devops, Angular,NodeJs',
    contactInfo: '0965656565',
    intro:
      'Tập đoàn Công nghiệp – Viễn thông Quân đội (Viettel) là doanh nghiệp kinh tế quốc phòng 100% vốn nhà nước, chịu trách nhiệm kế thừa các quyền, nghĩa vụ pháp lý và lợi ích hợp pháp của Tổng Công ty Viễn thông Quân đội',
    offeringJob: null,
    pendingCandidate: null,
    appliedCandidate: null,
  },
  {
    idCompany: 9,
    username: 'baseenterprise',
    name: 'Base EnterPrise',
    email: 'baseenterprise@gmail.com',
    image: 'https://cdn.topcv.vn/140/company_logos/cong-ty-co-phan-base-enterprise-5aa0e65f3f051_rs.jpg',
    location: 'HCM',
    jobsMain: 'BA, Tester, Mobile',
    contactInfo: '0965896543',
    intro: 'Base là công ty công nghệ được thành lập và vận hành bởi CEO của các công ty có nhiều kinh nghiệm trong thị trường công nghệ, ngân hàng, tài chính ở Việt Nam',
    offeringJob: null,
    pendingCandidate: null,
    appliedCandidate: null,
  },
  {
    idCompany: 10,
    username: 'cmctelecom',
    name: 'CMC Telecom',
    email: 'cmctelecom@gmail.com',
    image: 'https://cdn.topcv.vn/140/company_logos/cong-ty-co-phan-ha-tang-vien-thong-cmc-telecom-5af4f4a61b6e4_rs.jpg',
    location: 'HCM',
    jobsMain: 'Network, Data, Java',
    contactInfo: '0965656565',
    intro:
      'CMC Telecom là một trong 8 công ty thành viên của Tập đoàn Công nghệ CMC. Với gần 9 năm xây dựng, phát triển, CMC Telecom là công ty hạ tầng viễn thông nằm trong TOP 4 các công ty viễn thông hàng đầu Việt Nam',
    offeringJob: null,
    pendingCandidate: null,
    appliedCandidate: null,
  },
];
const candidates = [
  {
    idCandidate: 2,
    username: 'candidate1',
    name: 'Candidate1',
    image: 'https://cdn-icons-png.flaticon.com/512/219/219986.png',
    email: 'tungba100302@gmail.com',
    contactInfo: '096545453',
    workExperience: 'Fresher',
    skills: 'Java, NodeJS',
    education: 'VNU',
    summary: 'T have skills in Web Dev',
    location: 'HCM',
    appliedJob: '',
    pendingJob: '',
  },
  {
    idCandidate: 3,
    username: 'candidate2',
    name: 'Candidate2',
    image: 'https://cdn-icons-png.flaticon.com/512/219/219970.png',
    email: 'tungba100302@gmail.com',
    contactInfo: '0965656565',
    workExperience: 'Senior',
    skills: 'Python',
    education: 'HUST',
    summary: 'This is Summary',
    location: 'Da Nang',
    appliedJob: '',
    pendingJob: '',
  },
  {
    idCandidate: 4,
    username: 'candidate3',
    name: 'Candidate3',
    image: 'https://cdn-icons-png.flaticon.com/512/219/219988.png',
    email: 'tungba100302@gmail.com',
    contactInfo: '0965656565',
    workExperience: 'Junior',
    skills: 'NodeJS',
    education: 'HUST',
    summary: 'This is Summary',
    location: 'Ha Noi',
    appliedJob: '',
    pendingJob: '',
  },
  {
    idCandidate: 10,
    username: 'candidate4',
    name: 'Candidate4',
    image: 'https://cdn-icons-png.flaticon.com/512/219/219968.png',
    email: 'tungba100302@gmail.com',
    contactInfo: '0965656565',
    workExperience: 'Fresher',
    skills: 'Javascript',
    education: 'UET',
    summary: 'This is Summary',
    location: 'HCM',
    appliedJob: '',
    pendingJob: '',
  },
  {
    idCandidate: 11,
    username: 'candidate5',
    name: 'Candidate5',
    image: 'https://cdn-icons-png.flaticon.com/512/219/219988.png',
    email: 'tungba100302@gmail.com',
    contactInfo: '0965453423',
    workExperience: 'Junior',
    skills: 'Java,NodeJS,ReactJS',
    education: 'VNU',
    summary: 'I have experience in Web Development',
    location: 'Ha Noi',
    appliedJob: '',
    pendingJob: '',
  },
  {
    idCandidate: 12,
    username: 'candidate6',
    name: 'Candidate6',
    image: 'https://cdn-icons-png.flaticon.com/512/219/219970.png',
    email: 'tungba100302@gmail.com',
    contactInfo: '0965656565',
    workExperience: 'Junior',
    skills: 'NodeJS',
    education: 'HUST',
    summary: 'This is Summary',
    location: 'Ha Noi',
    appliedJob: '',
    pendingJob: '',
  },
  {
    idCandidate: 14,
    username: 'tungba1',
    name: 'TungBa',
    image: 'https://cdn-icons-png.flaticon.com/512/219/219986.png',
    email: 'tungba100302@gmail.com',
    contactInfo: '0965656565',
    workExperience: 'Junior',
    skills: 'NodeJS',
    education: 'HUST',
    summary: 'This is Summary',
    location: 'Ha Noi',
    appliedJob: null,
    pendingJob: null,
  },
];
const jobs = [
  {},
  {
    idJob: 2,
    name: 'IT Assistant',
    salary: '1000',
    level: 'Junior',
    typeOfTime: 'Full-time',
    typeOfWork: 'At Office',
    tags: 'Java, Python',
    location: 'Pham Ngu Lao Street, District 1, Ho Chi Minh',
    time: '20/11/2022',
    description: 'You will work directly',
    fromCompany: 'tungba2',
    pendingCandidate: '',
    appliedCandidate: 'tungba1',
    status: 'Pending',
  },
  {
    idJob: 3,
    name: 'Senior Product Owner',
    salary: '1100',
    level: 'Senior',
    typeOfTime: 'Full-time',
    typeOfWork: 'At office',
    tags: 'Java,Javascript',
    location: '458 Minh Khai, Hai Ba Trung, Ha Noi',
    time: '5/10/2022',
    description: 'You will work directly',
    fromCompany: 'tungba2',
    pendingCandidate: '',
    appliedCandidate: 'tungba1',
    status: 'Pending',
  },
  {
    idJob: 7,
    name: 'Java Developer',
    salary: '1200',
    level: 'Junior',
    typeOfTime: 'Part-time',
    typeOfWork: 'At Office',
    tags: 'Java',
    location: 'District 3, Ho Chi Minh',
    time: '20/11/2022',
    description: 'You will work directly',
    fromCompany: 'tungba2',
    pendingCandidate: '',
    appliedCandidate: 'tungba1',
    status: 'Pending',
  },
  {
    idJob: 8,
    name: 'Java Developer',
    salary: '1300',
    level: 'Junior',
    typeOfTime: 'Part-time',
    typeOfWork: 'At Office',
    tags: 'Java',
    location: 'District 3, Ho Chi Minh',
    time: '20/11/2022',
    description: 'You will work directly',
    fromCompany: 'tungba2',
    pendingCandidate: '',
    appliedCandidate: 'tungba1',
    status: 'Pending',
  },
  {
    idJob: 9,
    name: 'Java Developer',
    salary: '1400',
    level: 'Junior',
    typeOfTime: 'Part-time',
    typeOfWork: 'At Office',
    tags: 'Java',
    location: 'District 3, Ho Chi Minh',
    time: '20/11/2022',
    description: 'You will work directly',
    fromCompany: 'tungba2',
    pendingCandidate: '',
    appliedCandidate: 'tungba1',
    status: 'Pending',
  },
  {
    idJob: 10,
    name: 'Java Developer',
    salary: '1500',
    level: 'Junior',
    typeOfTime: 'Part-time',
    typeOfWork: 'At Office',
    tags: 'Java',
    location: 'District 3, Ho Chi Minh',
    time: '20/11/2022',
    description: 'You will work directly',
    fromCompany: 'tungba2',
    pendingCandidate: 'candidate1,candidate2,tungba1',
    appliedCandidate: null,
    status: 'Approving',
  },
  {
    idJob: 12,
    name: 'IT Development',
    salary: '1600',
    level: 'Junior',
    typeOfTime: 'Full-time',
    typeOfWork: 'At Office',
    tags: 'Java, Python',
    location: 'Nguyen Khanh Toan, Ho Chi Minh',
    time: '26/11/2002',
    description: 'You will be a hero',
    fromCompany: 'tungba2',
    pendingCandidate: 'candidate1,candidate2,tungba1',
    appliedCandidate: null,
    status: 'Approving',
  },
  {
    idJob: 13,
    name: 'IT Web Development',
    salary: '1700',
    level: 'Fresher',
    typeOfTime: 'Part-time',
    typeOfWork: 'At Office',
    tags: 'Java, Python',
    location: 'Nguyen Khanh Toan, Ho Chi Minh',
    time: '26/11/2002',
    description: 'You will be a hero',
    fromCompany: 'tungba2',
    pendingCandidate: 'candidate1,candidate2,candidate3',
    appliedCandidate: null,
    status: 'Approving',
  },
  {
    idJob: 17,
    name: 'Web',
    salary: '1800',
    level: 'Senior',
    typeOfTime: 'Part-time',
    typeOfWork: 'Online',
    tags: 'Java, Python',
    location: 'Nguyen, Ho Chi Minh',
    time: '26/11/2002',
    description: 'You will hero',
    fromCompany: 'tungba2',
    pendingCandidate: 'candidate3,candidate4',
    appliedCandidate: null,
    status: 'Approving',
  },
  {
    idJob: 60,
    name: 'Senior Android Developer ',
    salary: '1900',
    level: 'Senior',
    typeOfTime: 'Full-time',
    typeOfWork: 'At Office',
    tags: 'Java',
    location: '17 Duy Tan Street, Cau Giay District, Hanoi',
    time: '28/02/2023',
    description: 'Working in Global delivery team (US, China, India, Sing, VN,..)',
    fromCompany: 'fptsoftware',
    pendingCandidate: null,
    appliedCandidate: null,
    status: 'Pending',
  },
  {
    idJob: 61,
    name: 'Fresher Devops',
    salary: '2000',
    level: 'Fresher',
    typeOfTime: 'Part-time',
    typeOfWork: 'Online',
    tags: 'Devops',
    location: 'Ha Noi',
    time: '15/01/2023',
    description: ' Infrastructure as code',
    fromCompany: 'fptsoftware',
    pendingCandidate: null,
    appliedCandidate: null,
    status: 'Pending',
  },
  {
    idJob: 62,
    name: 'Fresher Automation Test',
    salary: '2100',
    level: 'Fresher',
    typeOfTime: 'Full-time',
    typeOfWork: 'At Office',
    tags: 'Tester',
    location: 'Ha Noi',
    time: '1/1/2023',
    description: 'Automation Testing for Web',
    fromCompany: 'fptsoftware',
    pendingCandidate: null,
    appliedCandidate: null,
    status: 'Pending',
  },
  {
    idJob: 63,
    name: 'Fresher C/Embedded',
    salary: '2200',
    level: 'Fresher',
    typeOfTime: 'Part-time',
    typeOfWork: 'Online',
    tags: 'C',
    location: 'Ha Noi',
    time: '1/2/2023',
    description: 'Embedded Software Development, Getting Started with KL46 freedom board',
    fromCompany: 'fptsoftware',
    pendingCandidate: null,
    appliedCandidate: null,
    status: 'Pending',
  },
  {
    idJob: 64,
    name: 'Java Developer',
    salary: '1100',
    level: 'Senior',
    typeOfTime: 'Full-time',
    typeOfWork: 'At Office',
    tags: 'Java',
    location: 'Keangnam Lanmark 72, Ha Noi',
    time: '9/12/2023',
    description: 'Unit test',
    fromCompany: 'vietteltelecom',
    pendingCandidate: null,
    appliedCandidate: null,
    status: 'Pending',
  },
  {
    idJob: 65,
    name: 'Data Scientist',
    salary: '1200',
    level: 'Senior',
    typeOfTime: 'Part-time',
    typeOfWork: 'Online',
    tags: 'Python',
    location: 'Keangnam Lanmark 72, Ha Noi',
    time: '28/2/2023',
    description: 'MAPE, Accuracy, Recall, Precision',
    fromCompany: 'vietteltelecom',
    pendingCandidate: null,
    appliedCandidate: null,
    status: 'Pending',
  },
  {
    idJob: 66,
    name: 'Tester',
    salary: '1300',
    level: 'Fresher',
    typeOfTime: 'Full-time',
    typeOfWork: 'At Office',
    tags: 'Tester',
    location: 'Keangnam Lanmark 72, Ha Noi',
    time: '31/1/2023',
    description: 'SQL, My SQL',
    fromCompany: 'vietteltelecom',
    pendingCandidate: null,
    appliedCandidate: null,
    status: 'Pending',
  },
  {
    idJob: 67,
    name: 'Security',
    salary: '1400',
    level: 'Senior',
    typeOfTime: 'Part-time',
    typeOfWork: 'Online',
    tags: 'Security',
    location: 'Keangnam Lanmark 72, Ha Noi',
    time: '31/1/2023',
    description: 'OWASP',
    fromCompany: 'vietteltelecom',
    pendingCandidate: null,
    appliedCandidate: null,
    status: 'Pending',
  },
  {
    idJob: 68,
    name: 'Customer Success Specialist (Background Ba)',
    salary: '1500',
    level: 'Senior',
    typeOfTime: 'Full-time',
    typeOfWork: 'At Office',
    tags: 'BA',
    location: 'Thanh Xuan, Ha Noi',
    time: '11/1/2023',
    description: 'Customer Success Specialist',
    fromCompany: 'baseenterprise',
    pendingCandidate: null,
    appliedCandidate: null,
    status: 'Pending',
  },
  {
    idJob: 69,
    name: 'Business Development (B2B Sales )',
    salary: '1600',
    level: 'Senior',
    typeOfTime: 'Part-time',
    typeOfWork: 'Online',
    tags: 'BD',
    location: 'Thanh Xuan, Ha Noi',
    time: '9/12/2023',
    description: 'Demonstration',
    fromCompany: 'baseenterprise',
    pendingCandidate: null,
    appliedCandidate: null,
    status: 'Pending',
  },
  {
    idJob: 70,
    name: 'Devops Engineer ',
    salary: '1700',
    level: 'Senior',
    typeOfTime: 'Full-time',
    typeOfWork: 'At Office',
    tags: 'Tester',
    location: 'Thanh Xuan, Ha Noi',
    time: '28/2/2023',
    description: ' Build and optimize CI/CD pipelines',
    fromCompany: 'baseenterprise',
    pendingCandidate: null,
    appliedCandidate: null,
    status: 'Pending',
  },
  {
    idJob: 71,
    name: 'Software Tester (Fresher)',
    salary: '2200',
    level: 'Fresher',
    typeOfTime: 'Part-time',
    typeOfWork: 'Online',
    tags: 'Java',
    location: 'Thanh Xuan, Ha Noi',
    time: '31/1/2023',
    description: 'Software Testers (Fresher)',
    fromCompany: 'baseenterprise',
    pendingCandidate: null,
    appliedCandidate: null,
    status: 'Pending',
  },
  {
    idJob: 72,
    name: 'IT',
    salary: '2500',
    level: 'Senior',
    typeOfTime: 'Full-time',
    typeOfWork: 'At Office',
    tags: 'Java',
    location: 'Duy Tan, Cau Giay',
    time: '15/01/2023',
    description: 'SQL, My SQL',
    fromCompany: 'cmctelecom',
    pendingCandidate: null,
    appliedCandidate: null,
    status: 'Pending',
  },
  {
    idJob: 73,
    name: 'TTS Network ',
    salary: '2700',
    level: 'Senior',
    typeOfTime: 'Part-time',
    typeOfWork: 'Online',
    tags: 'Network',
    location: 'Duy Tan, Cau Giay',
    time: '1/1/2023',
    description: 'Routing: stactic, OSPF, BGP; Switching: VTP, STP',
    fromCompany: 'cmctelecom',
    pendingCandidate: null,
    appliedCandidate: null,
    status: 'Pending',
  },
  {
    idJob: 74,
    name: 'Intern Network',
    salary: '2900',
    level: 'Fresher',
    typeOfTime: 'Full-time',
    typeOfWork: 'At Office',
    tags: 'Network',
    location: 'Duy Tan, Cau Giay',
    time: '31/1/2023',
    description: 'AON/GPON, Access / Metro / Core',
    fromCompany: 'cmctelecom',
    pendingCandidate: null,
    appliedCandidate: null,
    status: 'Pending',
  },
  {
    idJob: 75,
    name: 'Project Manager',
    salary: '3100',
    level: 'Senior',
    typeOfTime: 'Part-time',
    typeOfWork: 'Online',
    tags: 'Devops',
    location: 'Duy Tan, Cau Giay',
    time: '15/01/2023',
    description: 'VNPT, FPT, Viettel',
    fromCompany: 'cmctelecom',
    pendingCandidate: null,
    appliedCandidate: null,
    status: 'Pending',
  },
];

const companyItems = [];
companies.forEach((value) => {
  companyItems.push({
    path: `/companydetailjob/detail/${value.username}`,
    component: CompanyDetailJob,
  });
});
const candidateItems = [];
candidates.forEach((value) => {
  candidateItems.push({
    path: `/candidate/detail/${value.username}`,
    component: CandidateDetail,
  });
});
// const jobItems = [];
// companies.forEach((value) => {
//   jobItems.push({
//     path: `/jobdetailjob/detail/${value.username}`,
//     component: jobDetailJob,
//   });
// });

const publicRoutes = [
  { path: '/', component: CandidateHome },
  { path: '/home', component: CandidateHome },
  { path: '/job', component: JobSearchPage },
  { path: '/company', component: CompanyPage },
  { path: '/candidate', component: CandidatePage },
  { path: '/companydetailjob', component: CompanyDetailJob },
  { path: '/candidatedetail', component: CandidateDetail },
  ...companyItems,
  ...candidateItems,
];
const candidateRoutes = [
  { path: '/candidatehome', component: CandidateHome },
  { path: '/candidateprofile', component: CandidateProfilePage },
  { path: '/appliedjob', component: AppliedJob },
  { path: '/pendingjob', component: PendingJob },
];

const companyRoutes = [
  { path: '/companyhome', component: CompanyHome },
  { path: '/companyprofile', component: CompanyProfilePage },
  { path: '/pendingcandidate', component: PendingCandidate },
  { path: '/offeringjob', component: OfferingJobPage },
];
const adminRoutes = [
  {
    path: '/admin',
    component: ManageAccount,
  },
  {
    path: '/manageaccount',
    component: ManageAccount,
  },
  {
    path: '/managejob',
    component: ManageJob,
  },
];

const privateRoutes = [
  // Admin
  {
    path: '/admin',
    component: ManageAccount,
  },
  {
    path: '/home',
    component: ManageAccount,
  },
  {
    path: '/',
    component: ManageAccount,
  },
  {
    path: '/manageaccount',
    component: ManageAccount,
  },
  {
    path: '/managejob',
    component: ManageJob,
  },

  // Company + Candidate
  { path: '/', component: CompanyHome },
  { path: '/companyhome', component: CompanyHome },
  // { path: '/home/:username', component: Home },
  { path: '/companyprofile', component: CompanyProfilePage },
  { path: '/pendingcandidate', component: PendingCandidate },
  { path: '/offeringjob', component: OfferingJobPage },

  { path: '/candidatehome', component: CandidateHome },
  { path: '/candidateprofile', component: CandidateProfilePage },
  { path: '/appliedjob', component: AppliedJob },
  { path: '/pendingjob', component: PendingJob },
];

export { publicRoutes, privateRoutes, adminRoutes, candidateRoutes, companyRoutes };
